[versions]
springBoot = "3.3.4"
springDependencyManagement = "1.1.6"
protobufPlugin = "0.9.4"
protobuf = "3.25.5"
spotless = "6.25.0"
googleJavaFormat = "1.22.0"
springdoc = "2.6.0"
kafka = "3.8.0"
testcontainers = "1.20.2"
awaitility = "4.2.2"

[libraries]
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }

springdoc-webmvc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

postgresql = { module = "org.postgresql:postgresql", version = "42.7.4" }
flyway-core = { module = "org.flywaydb:flyway-core" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }

kafka-streams = { module = "org.apache.kafka:kafka-streams", version.ref = "kafka" }
kafka-streams-test-utils = { module = "org.apache.kafka:kafka-streams-test-utils", version.ref = "kafka" }

testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql" }
testcontainers-kafka = { module = "org.testcontainers:kafka" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
