plugins {
    id 'java-library'
    alias(libs.plugins.protobuf)
}

dependencies {
    // `api`: generated classes expose protobuf types.
    api libs.protobuf.java
}

protobuf {
    protoc {
        artifact = libs.protoc.get().toString()
    }
}

spotless {
    // Only generated code here.
    java {
        target 'src/main/java/**/*.java'
    }
}
