package com.alpian.payment.domain;

import java.util.Objects;
import java.util.UUID;

/**
 * Identifies a payment attempt.
 *
 * <p>Generated by the service, used as the journal row's primary key, and carried through to the
 * Kafka event as the consumer's deduplication key. It correlates a payment across the whole
 * pipeline — but note that it does <em>not</em> deduplicate client retries, because a retried
 * request would be assigned a fresh one. That is what {@link IdempotencyKey} is for.
 */
public record PaymentId(UUID value) {
  public PaymentId {
    Objects.requireNonNull(value, "value");
  }

  public static PaymentId generate() {
    return new PaymentId(UUID.randomUUID());
  }

  public static PaymentId of(String value) {
    return new PaymentId(UUID.fromString(value));
  }

  @Override
  public String toString() {
    return value.toString();
  }
}
